#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="ASLB")]
public partial class ASLBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public ASLBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASLBConnectionString"].ConnectionString + ";Application Name=ASLB" , mappingSource)
	{
		OnCreated();
	}
	
	public ASLBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ASLBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ASLBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ASLBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<GetSession> GetSessions
	{
		get
		{
			return this.GetTable<GetSession>();
		}
	}
	
	[Function(Name= "app.get_session")]
	public ISingleResult<GetSessionResult> GetSession([Parameter(Name = "ServiceName", DbType = "VarChar(50)")] string ServiceName, [Parameter(Name="DatabaseName", DbType="VarChar(50)")] string databaseName, [Parameter(Name="UserName", DbType="VarChar(100)")] string userName, [Parameter(Name="IPAddress", DbType="VarChar(100)")] string iPAddress, [Parameter(Name="Params", DbType="VarChar(100)")] string @params, [Parameter(Name="URL", DbType="VarChar(200)")] ref string uRL, [Parameter(Name="UseTCPIP", DbType="Bit")] System.Nullable<bool> useTCPIP)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ServiceName, databaseName, userName, iPAddress, @params, uRL, useTCPIP);
		uRL = ((string)(result.GetParameterValue(5)));
		return ((ISingleResult<GetSessionResult>)(result.ReturnValue));
	}
}

[Table(Name="")]
public partial class GetSession
{

    private string _ServiceName;

    private string _DatabaseName;
	
	private string _UserName;
	
	private string _IPAddress;
	
	private string _URL;
	
	private string _Params;
	
	public GetSession()
	{
	}

    [Column(Storage = "_ServiceName", CanBeNull = false)]
    public string ServiceName
    {
        get
        {
            return this._ServiceName;
        }
        set
        {
            if ((this._ServiceName != value))
            {
                this._ServiceName = value;
            }
        }
    }
    [Column(Storage= "_ServiceName", CanBeNull=false)]
	public string DatabaseName
	{
		get
		{
			return this._DatabaseName;
		}
		set
		{
			if ((this._DatabaseName != value))
			{
				this._DatabaseName = value;
			}
		}
	}
	
	[Column(Storage="_UserName", CanBeNull=false)]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this._UserName = value;
			}
		}
	}
	
	[Column(Storage="_IPAddress", CanBeNull=false)]
	public string IPAddress
	{
		get
		{
			return this._IPAddress;
		}
		set
		{
			if ((this._IPAddress != value))
			{
				this._IPAddress = value;
			}
		}
	}
	
	[Column(Storage="_URL", CanBeNull=false)]
	public string URL
	{
		get
		{
			return this._URL;
		}
		set
		{
			if ((this._URL != value))
			{
				this._URL = value;
			}
		}
	}
	
	[Column(Storage="_Params", CanBeNull=false)]
	public string Params
	{
		get
		{
			return this._Params;
		}
		set
		{
			if ((this._Params != value))
			{
				this._Params = value;
			}
		}
	}
}

public partial class GetSessionResult
{
	
	private string _ServerName;
	
	public GetSessionResult()
	{
	}
	
	[Column(Storage="_ServerName", DbType="VarChar(200)")]
	public string ServerName
	{
		get
		{
			return this._ServerName;
		}
		set
		{
			if ((this._ServerName != value))
			{
				this._ServerName = value;
			}
		}
	}
}
#pragma warning restore 1591
